In [1]:
!pip install selenium

Requirement already satisfied: selenium in /opt/anaconda3/lib/python3.8/site-packages (4.8.2)
Requirement already satisfied: certifi>=2021.10.8 in /opt/anaconda3/lib/python3.8/site-packages (from selenium) (2022.12.7)
Requirement already satisfied: trio-websocket~=0.9 in /opt/anaconda3/lib/python3.8/site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[socks]~=1.26 in /opt/anaconda3/lib/python3.8/site-packages (from selenium) (1.26.4)
Requirement already satisfied: trio~=0.17 in /opt/anaconda3/lib/python3.8/site-packages (from selenium) (0.22.0)
Requirement already satisfied: async-generator>=1.9 in /opt/anaconda3/lib/python3.8/site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in /opt/anaconda3/lib/python3.8/site-packages (from trio~=0.17->selenium) (20.3.0)
Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.8/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /opt/anaconda3/lib/python3.8/site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.8/site-packages (from trio~=0.17->selenium) (2.10)
Requirement already satisfied: sortedcontainers in /opt/anaconda3/lib/python3.8/site-packages (from trio~=0.17->selenium) (2.3.0)
Requirement already satisfied: outcome in /opt/anaconda3/lib/python3.8/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in /opt/anaconda3/lib/python3.8/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /opt/anaconda3/lib/python3.8/site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /opt/anaconda3/lib/python3.8/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [1]:
# 라이브러리 불러오기
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select

import time

In [2]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import urllib.request as req

from time import sleep

In [3]:
# 크롬 드라이버 잘 작동하는지 확인
driver = webdriver.Chrome() # 경로 지정해서 넣기
driver.get('https://esg.krx.co.kr/contents/02/02020000/ESG02020000.jsp')

In [4]:
#2023년 esg등급 표 스크랩 함수
def esg_2023_scraper():
    driver = webdriver.Chrome()
    driver.get('https://esg.krx.co.kr/contents/02/02020000/ESG02020000.jsp')
    time.sleep(10) # 웹사이트가 켜지는 시간동안 잠시 멈춤 합니다.
    
    ****** data_df_2023 # ****** 부분에 전역변수 설정 코드를 작성합니다.
    data_df_2023 = pd.DataFrame(columns=("회사명", "KCGS_종합등급", "KCGS_환경", "KCGS_사회", "KCGS_지배구조", "한국ESG연구소", "Moody's", "MSCI", "S&P", "연도"))
    
    index = 0

    while index < 792: # 총 페이지가 792장 있기 떄문에 <792로 제한을 둡니다.
        # 각 페이지의 테이블 가져오기
        table = ******.find_element(******)
        tbody = ******.find_element(******)
        rows = ******.find_elements(******)
        
        # 한 페이지 속 기업들(rows)에 대해
        for i in range(len(rows)):
            # 매번 새로운 rows를 가져옵니다.
            rows = ******.find_elements(******) # 위에 rows = ******.find_elements(******) 랑 동일
            row = rows[i]
            # 기업명
            company_name = row.find_element(******, ******).******
            # KCGS_종합 등급 
            kcgs_1 = row.find_elements(******, ******)[*].******
            # KCGS_환경 등급
            kcgs_2 = row.find_elements(******, ******)[*].******
            # KCGS_사회 등급
            kcgs_3 = row.find_elements(******, ******)[*].******
            # KCGS_지배구조 등급
            kcgs_4 = row.find_elements(******, ******)[*].******
            #한국ESG연구소 등급
            kesg = row.find_elements(******, ******)[*].******
            # Moody's 등급
            moodys = row.find_elements(******, ******)[*].******
            # MSCI 등급
            msci = row.find_elements(******, ******)[*].******
            # S&P 등급
            sp = row.find_elements(******, ******)[*].******
            # 연도
            year = row.find_elements(******, ******)[*].******
            
            # 기업별 추출한 정보를 dataframe의 한 행으로 저장
            data_df_2023.***[******] = [company_name, kcgs_1, kcgs_2, kcgs_3, kcgs_4, kesg, moodys, msci, sp, year]
            
            # index를 증가시키기 -> while이 반복되며 index가 792가 되면 종료
            index += 1
        
        # 한 페이지 내에는 10개의 row(기업) 존재,
        # 10개 기업 데이터 모두 추출한 후에는 다음 페이지로 이동
        if index % 10 == 0:
            next_page = driver.find_element(*****.*****, *****)
            driver.execute_script(*****, next_page)
            time.sleep(10)

    print(data_df_2023)
    return data_df_2023

In [3]:
#2022년 esg등급 표 스크랩 함수
def esg_2022_scraper():
    driver = webdriver.Chrome()
    driver.get('https://esg.krx.co.kr/contents/02/02020000/ESG02020000.jsp')
    time.sleep(10)
    
    # 연도를 2022년으로 바꾸고 정보 조회
    select = Select(driver.find_element(***.***, ***))
    select.select_by_value(***)
    driver.find_element(***.***, ***).click()
    time.sleep(10)
    
    # 위 esg_2023_scraper 2023 코드랑 동일
    ###
    ###
    ###
    ###
    ###   
    ###
    ###
    ###
    ###
    ###
    

    print(data_df_2022)
    return data_df_2022

In [6]:
#2021년 esg등급 표 스크랩 함수
def esg_2022_scraper():
    driver = webdriver.Chrome()
    driver.get('https://esg.krx.co.kr/contents/02/02020000/ESG02020000.jsp')
    time.sleep(10)
    
    # 연도를 2021년으로 바꾸고 정보 조회
    select = Select(driver.find_element(***.***, ***))
    select.select_by_value(***)
    driver.find_element(***.***, ***).click()
    time.sleep(10)
    
    # 위 esg_2023_scraper 2023 코드랑 동일
    ###
    ###
    ###
    ###
    ###   
    ###
    ###
    ###
    ###
    ###
    

    print(data_df_2022)
    return data_df_2022

In [7]:
#2020년 esg등급 표 스크랩 함수
def esg_2022_scraper():
    driver = webdriver.Chrome()
    driver.get('https://esg.krx.co.kr/contents/02/02020000/ESG02020000.jsp')
    time.sleep(10)
    
    # 연도를 2020년으로 바꾸고 정보 조회
    select = Select(driver.find_element(***.***, ***))
    select.select_by_value(***)
    driver.find_element(***.***, ***).click()
    time.sleep(10)
    
    # 위 esg_2023_scraper 2023 코드랑 동일
    ###
    ###
    ###
    ###
    ###   
    ###
    ###
    ###
    ###
    ###
    

    print(data_df_2022)
    return data_df_2022

In [10]:
esg_2023_scraper()

           회사명 KCGS_종합등급 KCGS_환경 KCGS_사회 KCGS_지배구조 한국ESG연구소 Moody's MSCI S&P  \
0       AJ네트웍스        B+       C      B+        B+        -       -    -   -
1        AK홀딩스        B+       B       A         B        -       -    -   4
2          BGF        B+       A      A+         B        -       -    -  18
3       BGF리테일         A       A      A+         A        A      23  BBB  58
4      BNK금융지주         A       A       A         A        A      37    A  43
..         ...       ...     ...     ...       ...      ...     ...  ...  ..
787  휴니드테크놀러지스         D       D       C         C        -       -    -   -
788        휴비스        B+      B+       A        B+        -       -    -   6
789        휴스틸         D       D       D         C        -       -    -   -
790       흥국화재        B+       C      B+        B+        -       -    -   -
791       흥아해운         C       C       B         C        -       -    -   -

       연도
0    2023
1    2023
2    2023
3    2023
4    2023
..    ...
787  2023
788  2023
789  2023
790  2023
791  2023

[792 rows x 10 columns]

,회사명,KCGS_종합등급,KCGS_환경,KCGS_사회,KCGS_지배구조,한국ESG연구소,Moody's,MSCI,S&P,연도
0,AJ네트웍스,B+,C,B+,B+,-,-,-,-,2023
1,AK홀딩스,B+,B,A,B,-,-,-,4,2023
2,BGF,B+,A,A+,B,-,-,-,18,2023
3,BGF리테일,A,A,A+,A,A,23,BBB,58,2023
4,BNK금융지주,A,A,A,A,A,37,A,43,2023
...,...,...,...,...,...,...,...,...,...,...
787,휴니드테크놀러지스,D,D,C,C,-,-,-,-,2023
788,휴비스,B+,B+,A,B+,-,-,-,6,2023
789,휴스틸,D,D,D,C,-,-,-,-,2023
790,흥국화재,B+,C,B+,B+,-,-,-,-,2023
791,흥아해운,C,C,B,C,-,-,-,-,2023

In [12]:
esg_2022_scraper()

           회사명 KCGS_종합등급 KCGS_환경 KCGS_사회 KCGS_지배구조 한국ESG연구소 Moody's MSCI S&P  \
0       AJ네트웍스        B+       C      B+        B+        -       -    -   -
1        AK홀딩스        B+       B       A         B        -       -    -   4
2          BGF        B+       A      A+         B        -       -    -  18
3       BGF리테일         A       A      A+         A        A      23  BBB  58
4      BNK금융지주         A       A       A         A        A      37    A  43
..         ...       ...     ...     ...       ...      ...     ...  ...  ..
787  휴니드테크놀러지스         D       D       C         C        -       -    -   -
788        휴비스        B+      B+       A        B+        -       -    -   6
789        휴스틸         D       D       D         C        -       -    -   -
790       흥국화재        B+       C      B+        B+        -       -    -   -
791       흥아해운         C       C       B         C        -       -    -   -

       연도
0    2022
1    2022
2    2022
3    2022
4    2022
..    ...
787  2022
788  2022
789  2022
790  2022
791  2022

[792 rows x 10 columns]

,회사명,KCGS_종합등급,KCGS_환경,KCGS_사회,KCGS_지배구조,한국ESG연구소,Moody's,MSCI,S&P,연도
0,AJ네트웍스,B+,C,B+,B+,-,-,-,-,2022
1,AK홀딩스,B+,B,A,B,-,-,-,4,2022
2,BGF,B+,A,A+,B,-,-,-,18,2022
3,BGF리테일,A,A,A+,A,A,23,BBB,58,2022
4,BNK금융지주,A,A,A,A,A,37,A,43,2022
...,...,...,...,...,...,...,...,...,...,...
787,휴니드테크놀러지스,D,D,C,C,-,-,-,-,2022
788,휴비스,B+,B+,A,B+,-,-,-,6,2022
789,휴스틸,D,D,D,C,-,-,-,-,2022
790,흥국화재,B+,C,B+,B+,-,-,-,-,2022
791,흥아해운,C,C,B,C,-,-,-,-,2022

In [25]:
esg_2021_scraper()

           회사명 KCGS_종합등급 KCGS_환경 KCGS_사회 KCGS_지배구조 한국ESG연구소 Moody's MSCI S&P  \
0       AJ네트웍스         B       D       B         B        -       -    -   -
1        AK홀딩스        B+       B      B+        B+        -       -    -   1
2          BGF         A       A      A+         A        -       -    -  13
3       BGF리테일         A       A      A+         A        S       -  BBB  11
4      BNK금융지주        A+       A      A+        A+        A       -    A  38
..         ...       ...     ...     ...       ...      ...     ...  ...  ..
787  휴니드테크놀러지스         B       C      B+        B+        -       -    -   -
788        휴비스         A      B+      A+         A        -       -    -   5
789        휴스틸         C       C       C         B        -       -    -   -
790       흥국화재        B+       B       A         B        -       -    -   -
791       흥아해운         D       D       C         D        -       -    -   -

       연도
0    2021
1    2021
2    2021
3    2021
4    2021
..    ...
787  2021
788  2021
789  2021
790  2021
791  2021

[792 rows x 10 columns]

,회사명,KCGS_종합등급,KCGS_환경,KCGS_사회,KCGS_지배구조,한국ESG연구소,Moody's,MSCI,S&P,연도
0,AJ네트웍스,B,D,B,B,-,-,-,-,2021
1,AK홀딩스,B+,B,B+,B+,-,-,-,1,2021
2,BGF,A,A,A+,A,-,-,-,13,2021
3,BGF리테일,A,A,A+,A,S,-,BBB,11,2021
4,BNK금융지주,A+,A,A+,A+,A,-,A,38,2021
...,...,...,...,...,...,...,...,...,...,...
787,휴니드테크놀러지스,B,C,B+,B+,-,-,-,-,2021
788,휴비스,A,B+,A+,A,-,-,-,5,2021
789,휴스틸,C,C,C,B,-,-,-,-,2021
790,흥국화재,B+,B,A,B,-,-,-,-,2021
791,흥아해운,D,D,C,D,-,-,-,-,2021

In [14]:
esg_2020_scraper()

           회사명 KCGS_종합등급 KCGS_환경 KCGS_사회 KCGS_지배구조 한국ESG연구소 Moody's MSCI S&P  \
0       AJ네트웍스         B       D       B         B        -       -    -   -
1        AK홀딩스        B+       C      B+        B+        -       -    -   -
2          BGF        B+       B       A        B+        -       -    -   -
3       BGF리테일         A      B+      B+         A        -       -   BB   -
4      BNK금융지주        A+      B+      A+        A+        -       -    A   -
..         ...       ...     ...     ...       ...      ...     ...  ...  ..
787  휴니드테크놀러지스         C       C       B         B        -       -    -   -
788        휴비스        B+      B+      B+        B+        -       -    -   -
789        휴스틸         C       B       B         C        -       -    -   -
790       흥국화재         B       D       A         B        -       -    -   -
791       흥아해운         D       D       C         D        -       -    -   -

       연도
0    2020
1    2020
2    2020
3    2020
4    2020
..    ...
787  2020
788  2020
789  2020
790  2020
791  2020

[792 rows x 10 columns]

,회사명,KCGS_종합등급,KCGS_환경,KCGS_사회,KCGS_지배구조,한국ESG연구소,Moody's,MSCI,S&P,연도
0,AJ네트웍스,B,D,B,B,-,-,-,-,2020
1,AK홀딩스,B+,C,B+,B+,-,-,-,-,2020
2,BGF,B+,B,A,B+,-,-,-,-,2020
3,BGF리테일,A,B+,B+,A,-,-,BB,-,2020
4,BNK금융지주,A+,B+,A+,A+,-,-,A,-,2020
...,...,...,...,...,...,...,...,...,...,...
787,휴니드테크놀러지스,C,C,B,B,-,-,-,-,2020
788,휴비스,B+,B+,B+,B+,-,-,-,-,2020
789,휴스틸,C,B,B,C,-,-,-,-,2020
790,흥국화재,B,D,A,B,-,-,-,-,2020
791,흥아해운,D,D,C,D,-,-,-,-,2020

In [26]:
data_df_2023.to_csv('esg_2023.csv')
data_df_2022.to_csv('esg_2022.csv')
data_df_2021.to_csv('esg_2021.csv')
data_df_2020.to_csv('esg_2020.csv')

In [28]:
# 데이터 합치기
data_df_merge = pd.concat([************, ************, ************, ************])
data_df_merge

,회사명,KCGS_종합등급,KCGS_환경,KCGS_사회,KCGS_지배구조,한국ESG연구소,Moody's,MSCI,S&P,연도
0,AJ네트웍스,B+,C,B+,B+,-,-,-,-,2023
1,AK홀딩스,B+,B,A,B,-,-,-,4,2023
2,BGF,B+,A,A+,B,-,-,-,18,2023
3,BGF리테일,A,A,A+,A,A,23,BBB,58,2023
4,BNK금융지주,A,A,A,A,A,37,A,43,2023
...,...,...,...,...,...,...,...,...,...,...
787,휴니드테크놀러지스,C,C,B,B,-,-,-,-,2020
788,휴비스,B+,B+,B+,B+,-,-,-,-,2020
789,휴스틸,C,B,B,C,-,-,-,-,2020
790,흥국화재,B,D,A,B,-,-,-,-,2020
791,흥아해운,D,D,C,D,-,-,-,-,2020

In [33]:
# 정렬하기
data_df_merge.sort_values(by=['회사명', '연도'], inplace = True)
data_df_merge

,회사명,KCGS_종합등급,KCGS_환경,KCGS_사회,KCGS_지배구조,한국ESG연구소,Moody's,MSCI,S&P,연도
0,AJ네트웍스,B,D,B,B,-,-,-,-,2020
0,AJ네트웍스,B,D,B,B,-,-,-,-,2021
0,AJ네트웍스,B+,C,B+,B+,-,-,-,-,2022
0,AJ네트웍스,B+,C,B+,B+,-,-,-,-,2023
1,AK홀딩스,B+,C,B+,B+,-,-,-,-,2020
...,...,...,...,...,...,...,...,...,...,...
790,흥국화재,B+,C,B+,B+,-,-,-,-,2023
791,흥아해운,D,D,C,D,-,-,-,-,2020
791,흥아해운,D,D,C,D,-,-,-,-,2021
791,흥아해운,C,C,B,C,-,-,-,-,2022
791,흥아해운,C,C,B,C,-,-,-,-,2023

In [34]:
# 저장하기
data_df_merge.to_csv('esg_merge.csv', encoding='utf-8-sig')